In [5]:
import pandas as pd
import numpy as np

# Definir alturas y días del mes
alturas = ['Altura1', 'Altura2', 'Altura3']
dias_del_mes = [f'Día{i+1}' for i in range(30)]

# Generar datos aleatorios de temperaturas
np.random.seed(0)  # Para reproducibilidad
data = {
    altura: np.random.uniform(low=-10, high=35, size=len(dias_del_mes))
    for altura in alturas
}

# Crear el DataFrame
df = pd.DataFrame(data, index=dias_del_mes)

# Calcular la media de las temperaturas para cada altura
df.loc['Media'] = df.mean(axis=0)

# Mostrar el DataFrame
df

         Altura1    Altura2    Altura3
Día1   14.696608   1.905003  -2.846369
Día2   22.183521  24.840516  -5.033119
Día3   17.124352  10.526765  19.534832
Día4   14.519743  15.579528  -3.781767
Día5    9.064466  -9.154459  -1.153794
Día6   19.065235  17.793597   6.592633
Día7    9.691425  17.544308  26.944695
Día8   30.129785  17.762030  -5.630443
Día9   33.364824  32.468664  27.707521
Día10   7.254868  20.681913  -5.675572
Día11  25.627627   6.177856  33.940676
Día12  13.800271   9.666438  11.089304
Día13  15.562005  21.393404  33.954249
Día14  31.651849  -7.289854  17.218048
Día15  -6.803377  20.004502  23.266861
Día16  -6.079182  20.178704  -8.236549
Día17  -9.090172  -0.532785   2.726313
Día18  27.467893  -4.198317  -4.591155
Día19  25.017054   4.194276   3.326309
Día20  29.150547   6.366985  -4.657253
Día21  34.037825  15.658855   4.309243
Día22  25.962135   9.737068   8.641835
Día23  10.766571  34.476823  -7.113363
Día24  25.123813  -5.407984  21.161245
Día25  -4.677651  -0.600546  15.497065
Día26  18.796446  -2.741072   1.942527
Día27  -3.549102  19.389875  13.546162
Día28  32.510101   1.398122  -5.772677
Día29  13.483174  10.983985  15.917592
Día30   8.659787   0.999152  31.818329
Media  16.150415  10.326778   8.821446